import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Footer from "@/components/UI/Footer/Footer.component.page";
import Root from "./root";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog.dev | Blog dla Web developerów",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Root children={children} />
  );
}
